global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Text.Encodings.Web;
global using System.Text.Json;
global using System.Threading.Tasks;
global using Cross.ErrorHandlers.Exceptions;
global using Cross.ErrorHandlers.Models;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Primitives;
global using ValidationException = FluentValidation.ValidationException;
